version: '3.2'

services:
  my-rabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'myRabbit'
    environment:
      - RABBITMQ_DEFAULT_USER=henrique
      - RABBITMQ_DEFAULT_PASS=gtcanime
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.doccker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - nacos_net

networks:
    nacos_net:
      ipam:
        driver: default
        config:
            - subnet: "10.0.2.0/24"